// userAuth
export const REQUEST_LOG_USER = 'REQUEST_LOG_USER'
export const RECEIVED_LOG_USER = 'RECEIVED_LOG_USER'
export const ERROR_LOG_USER = 'ERROR_LOG_USER'
export const CHECK_IF_AUTHENTICATED = 'CHECK_IF_AUTHENTICATED'
export const DISCONNECT_USER = 'DISCONNECT_USER'

// users
export const USERS_GET_REQUEST = 'USERS_GET_REQUEST'
export const USERS_GET_SUCCESS = 'USERS_GET_SUCCESS'
export const USERS_GET_ERROR = 'USERS_GET_ERROR'

export const USER_ADD_REQUEST = 'USER_ADD_REQUEST'
export const USER_ADD_SUCCESS = 'USER_ADD_SUCCESS'
export const USER_ADD_ERROR = 'USER_ADD_ERROR'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_ERROR = 'USER_UPDATE_ERROR'

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST'
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS'
export const USER_DELETE_ERROR = 'USER_DELETE_ERROR'


// fetchMiddleware
export const FETCH_MIDDLEWARE = 'FETCH_MIDDLEWARE'

// views
export const ENTER_VIEW = 'ENTER_VIEW'

export const REQUEST_PHOTO_FETCH  = 'REQUEST_PHOTO_FETCH';
export const RECEIVED_PHOTO_FETCH = 'RECEIVED_PHOTO_FETCH';
export const ERROR_PHOTO_FETCH    = 'ERROR_PHOTO_FETCH';